ESS\UserBundle\Entity\User:
    type: entity
    table: ess_user
    indexes:
        idx_ad8a54a9979b1ad6:
            columns:
                - company_id
    uniqueConstraints:
        uniq_ad8a54a9f85e0677:
            columns:
                - username
        uniq_ad8a54a9e7927c74:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        username:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        token:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        isActive:
            type: boolean
            nullable: true
            comment: ''
            column: is_active
        createdAt:
            type: datetime
            nullable: false
            comment: ''
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            comment: ''
            column: updated_at

    lifecycleCallbacks: 
        prePersist: [ setCreatedAtValue ]
